### ISSUE TITLE
User can view favorite entries

### ISSUE THREAD

**Issue by seankim248** [seankim248/code-journal#10]
## 💰 Motivation

Once a user records some journal entries, they'll want to see them but also would want to save some entries for easier access.

## 📐 Plan

Display the user's journal favorited entries.

## ✅ Task List

- [x] Add a favorites tab next to the entries tab
- [x] Add a sibling `div[data-view="favorites"]` element in the HTML.
- [x] Add a favorite icon next to the edit icon
- [x] Add a favorite array in the data model
- [ ] Change the icon so that when a user presses it, it changes colors and appends it to the favorite array in the data model
- [ ] When the user presses the favorites tab, the view should be swapped to the favorites view with the favorited entries
- [ ] When a user clicks a favorited entry, it gets rid of the entry from the favorites view, deletes it from the favorites array, and should revert back to original color
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
